spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: springboot-mybatisplus-shardingjdbc
  thymeleaf:
    cache: false
    mode: HTML

sharding.jdbc:
  data-sources:
    ds_master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/tzn?allowMultiQueries=true&useUnicode=yes&characterEncoding=utf8&serverTimezone=GMT%2B8
      username: root
      password: root
    ds_slave_0:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/tzn?allowMultiQueries=true&useUnicode=yes&characterEncoding=utf8&serverTimezone=GMT%2B8
      username: root
      password: root
  master-slave-rule:
    name: ds_ms
    master-data-source-name: ds_master
    slave-data-source-names: ds_slave_0
    load-balance-algorithm-type: round_robin
    props:
      sql.show: true
